---

- name: "Add Visual Studio Code Repository"
  ansible.builtin.yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  become: true

- name: "Install Visual Studio Code"
  ansible.builtin.dnf:
    name: code
  become: true