# -*- mode: ruby -*-
# vi: set ft=ruby :
VM_LIST = {
  "test1" => {
    :ip => "192.168.56.210",
    :cpus => 2,
    :memory => 4_096,
    :disksize => "64GB"
  },
  "test2" => {
    :ip => "192.168.56.211",
    :cpus => 2,
    :memory => 4_096,
    :disksize => "64GB"
  },
  "test3" => {
    :ip => "192.168.56.212",
    :cpus => 2,
    :memory => 4_096,
    :disksize => "64GB"
  },
}
GATEWAY = "192.168.56.254"

Vagrant.configure("2") do |config|
  # Get Virtual Machine names
  vm_names = VM_LIST.keys

  # Get IP list
  ips = VM_LIST.map { |_, config| config[:ip] }

  # Define groups
  group_hash = vm_names.each_with_object({}) do |hostname, hash|
    hash["group_#{hostname}"] = [hostname]
  end
  group_hash["rocky810"] = vm_names
  group_hash["all:children"] = vm_names

  VM_LIST.each do |hostname, opts|
    config.vm.define hostname do |node|
      node.vm.box = "bento/rockylinux-8.10"
      node.vm.hostname = hostname
      node.vm.disk :disk, size: opts[:disksize], primary: true
      node.vm.synced_folder '.', '/vagrant', disabled: true

      # Bridge
      node.vm.network :public_network,
        :dev => "br0",
        :mode => "bridge",
        :type => "bridge",
        :ip => opts[:ip],
        :netmask => "255.255.255.0",
        :gateway => GATEWAY
      
      config.vm.provision "shell", inline: <<-SHELL
        nmcli connection modify "System eth1" ipv4.route-metric 50
        systemctl restart NetworkManager
      SHELL

      node.vm.provider :libvirt do |libvirt|
        libvirt.nested = true
        libvirt.cpu_mode = "host-passthrough"
        libvirt.cpus = opts[:cpus]
        libvirt.memory = opts[:memory]
      end
    end
  end

  # SSH settings
  config.vm.provision "shell", path: "../../provisioning/shell/ssh.sh", args: ips

  # Install prerequisites
  config.vm.provision "shell", path: "../../provisioning/shell/prerequisites.sh"

  # Run playbook
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../provisioning/playbooks/playbook.yml"
    ansible.groups = group_hash
    ansible.extra_vars = {
      ansible_python_interpreter: "/usr/bin/python3"
    }
    ansible.compatibility_mode = "2.0"
  end
end
