---

- hosts: all
  tasks:
    - name: "Install dnf-utils"
      ansible.builtin.dnf:
        name: dnf-utils
        state: present
      become: true

    - name: "Add HashiCorp Repository"
      ansible.builtin.yum_repository:
        name: HashiCorp
        description: HashiCorp Stable Repository
        baseurl: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
      become: true

    - name: "install prerequisite"
      ansible.builtin.dnf:
        name:
          - git
          - vagrant
          - ansible 
      become: true